; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=MataElHambre
AppVersion=1.4
DefaultDirName={pf}\MataElHambre
DefaultGroupName=MataElHambre
OutputBaseFilename=MataElHambre_Instalador
Compression=lzma
SolidCompression=yes

[Files]
Source: "dist\run_pos.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\db.sqlite3"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\core\*"; DestDir: "{app}\core"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{group}\MataElHambre"; Filename: "{app}\run_pos.exe"

[Run]
Filename: "{app}\run_pos.exe"; Description: "Iniciar MataElHambre"; Flags: nowait postinstall skipifsilent
