# Generated by Django 5.2.1 on 2025-06-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredientes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
