# Generated by Django 5.2.1 on 2025-06-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cliente_remove_comanda_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='venta',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Detalle',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
