# Generated by Django 5.2.1 on 2025-06-24 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_historialcomanda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcomanda',
            name='cerrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialcomanda',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialcomanda',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historialcomanda',
            name='nombre_cliente',
            field=models.CharField(max_length=100),
        ),
    ]
