# Generated by Django 5.2.1 on 2025-06-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historialcomanda_cerrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('promos', 'Promos'), ('hamburguesas', 'Hamburguesas'), ('chorrillanas', 'Chorrillanas'), ('sandwiches', 'Sandwiches'), ('as', 'As'), ('sandwich_pescado', 'Sandwich Pescado'), ('vienesas', 'Vienesas'), ('empanadas', 'Empanadas Fritas'), ('papas', 'Papas')], default='promos', max_length=20),
        ),
    ]
