# Generated by Django 5.2.1 on 2025-06-30 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminacionComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comanda_id', models.IntegerField()),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField()),
                ('motivo', models.TextField()),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('eliminado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
