# Generated by Django 5.2.1 on 2025-07-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_comanda_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='monto_transferencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialcomanda',
            name='monto_transferencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
