# Generated by Django 5.2.1 on 2025-07-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_impresora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Impresora',
        ),
    ]
